apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twvault.scripts.secretName" . }}
  labels:
    {{- include "twvault.commonLabels" "app" | nindent 4 -}}
type: Opaque
data:
  vault.js: {{ .Files.Get .Values.script.vault | b64enc }}
  main.js: {{ .Files.Get .Values.script.main | b64enc }}