{{- if not .Values.postgresOnly -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twvault.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "twvault.name" . }}-app
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "twvault.name" . }}-app
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}